### ISSUE TITLE
linking posts to categories

### ISSUE THREAD

**Issue by drjsoundsgood** [drjsoundsgood/PP#2]
When I try to add a post to a category, I get the following error:

MultiValueDictKeyError at /dicer/category/may-hem/add_post/
"'query'"

This is the traceback:
Traceback:
File "/Library/Python/2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/jonesy/CODE/PP/dicer/views.py" in add_post
  183.                 return category(request, category_name_slug)
File "/Users/jonesy/CODE/PP/dicer/views.py" in category
  94.         query = request.POST['query'].strip()
File "/Library/Python/2.7/site-packages/django/utils/datastructures.py" in __getitem__
  319.             raise MultiValueDictKeyError(repr(key))

I have gotten this error before (see issue #1).

The post gets saved to my admin interface, but does not get displayed in its respective category.

Any ideas?

**Comment by bjerre** [comment]
Hi Jonesy,
The message is pretty much saying that the POST XML or JSON sent from the web browser when you click add category doesn't have a 'query' key. 

It's certainly failing here:
def category(request, category_name_slug):
    context_dict = {}
    context_dict['result_list'] = None
    context_dict['query'] = None
    if request.method == 'POST':
        **query = request.POST['query'].strip()**

If the query line were written query = request.POST.get('query','').strip() it wouldn't fail there. But it looks like that's view function is boilderplate django blog demo. However it looks like the POST request generated when you click is expecting a 'query' item. Otherwise they would have caught the exception.

My first step would be to navigate to the page where the error was generated and open up Chrome's developer console (F12). If you click on the network tab you can see the packets being exchanged. When you click on add category, look at the content of the 'POST' XML packets sent back to the server.

**Comment by drjsoundsgood** [comment]
Hi Dan,

Okay. This is great. The error is gone, but the posts don't appear where they should.

Any idea as to why my posts don't show up on their respective category page?

This is the template tag I have in my category.html:

        {% if posts %}
        <ul>
            {% for post in posts %}


                <li><a>{{ post.title }}</a></li>
                <li>{{ post.text|linebreaks }}</li>
            {% endfor %}
        </ul>
            {% else %}
            <p>There are no posts.</p>
        {% endif %}
